server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:3306/cetus?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;serverTimezone=GMT%2B8
    username: root
    password: Evan1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.cetus.entity