server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://10.0.2.18:5432/urp_hsbc?currentSchema=public
    username: urp_hsbc
    password: urp_hsbc
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.cetus.entity