spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cetus?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Evan1234
    driverClassName: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8080
  servlet:
    context-path: /cetus

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#  mybatis.type-aliases-package= com.cetus.mapper
# type: com.alibaba.druid.pool.DruidDataSource4
#logging.level.org.springframework.boot.autoconfigure=ERROR